### ISSUE TITLE
detect.excluded.directories not working and ignored

### ISSUE THREAD

**Issue by tvcsantos** [blackduck-inc/black-duck-security-scan#41]
While trying to exclude directories from black duck scan we found out that they don't take effect

![Image](https://github.com/user-attachments/assets/ce00ad2b-5923-4f35-9a40-f0f47e9b4fe8)

```yaml
detect:
  maven:
    excluded:
      scopes: test
  excluded:
    directories: .mvn
````

We have the following in detect configuration file. As you can see `.mvn` directory is not being added and `.bridge` is taking over.

Can you check what is happening

Thanks
