### ISSUE TITLE
Cannot get PR Commenter to work

### ISSUE THREAD

**Issue by jnus** [blackduck-inc/black-duck-security-scan#42]
Been trying to get PR commenting to work, however unsuccessfully so far. Facts
1. Scans are uploaded correctly to BD
2. I see the result in the logs as well.
3. Running self hosted runner and GHES. 

Workflow:
```yaml
...
permissions:
  pull-requests: write
  issues: write
  contents: read
...
    - name: Black Duck SCA PR Scan
      if: ${{ github.event_name == 'pull_request' }}
      uses: blackduck-inc/black-duck-security-scan@805cbd09e806b01907bbea0f990723c2bb85abe9
      env:
        DETECT_PROJECT_NAME: ${{ inputs.DETECT_PROJECT_NAME }}
      with:
        blackducksca_url: ${{ inputs.black_duck_url  }}
        blackducksca_token: ${{ inputs.black_duck_token }}
        blackducksca_scan_full: false
        blackducksca_prComment_enabled: true
        github_token: ${{ inputs.github_token }}
        include_diagnostics: true
```

I also see the PR Commenter adapter being started and stopped. However no comments are added to the PR. Furthermore I see that a status file is generated. E.g. 

>  /opt/actions-runner/_work/[repo]/[repo]/.bridge/Blackduck SCA Detect Execution/detect/runs/2025-01-27-15-35-21-129/status/status.json

In the diagnostic logs i see that the PR Commenter has been run with the following:

> /home/runners/bridge-cli-bundle/bridge-cli-bundle-linux64/adapters/github-commenter/versions/0.2.73/github-commenter /opt/actions-runner/_work/[repo]/[repo]/.bridge/GitHub Commenter/data.json

Any advice on how to troubleshoot this, is greatly appreciated.
